require 'spec/rails/matchers/active_record'
require 'spec/rails/matchers/observers'
require 'spec/rails/matchers/associations'
require 'spec/rails/matchers/validations'
require 'spec/rails/matchers/views'
require 'spec/rails/matchers/observers'
